# Generated by Django 5.0.7 on 2024-07-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_description_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='release',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/shop/images'),
        ),
    ]
